### PR TITLE
Minor updates

### PR DESCRIPTION
**Pull request by mosabua**
Just set it up so it works nicely with new versions for a bunch of plugins and dependencies..

### CODE REVIEW

**Comment by mttkay** [comment]
thanks, looks good!

**Comment by mttkay** [comment]
I'm trying to merge in your changes, but the project doesn't build anymore. That's because the JUnit 4 dependency shadows the JUnit 3 dependency from android-test, even though JUnit 4 has test scope and JUnit 3 has provided scope. Any idea why that is?

**Comment by mosabua** [comment]
whoa.. thats weird

I will check it out

**Comment by mosabua** [comment]
provided scope works... am although that feels wrong

**Comment by mttkay** [comment]
It seems this was caused by the change to the PowerMock module names in the POM. Why was that change necessary? Were the ones I used deprecated or something?

**Comment by mosabua** [comment]
I could not find the original artifacts and these ones where the best I could find.. might be wrong..

**Comment by mttkay** [comment]
I didn't found a better solution, so I used the provided scope for JUnit 4 as you suggested. Works fine.

**Comment by mosabua** [comment]
Me neither. Maybe just document that in the pom a bit I guess.

**Comment by mttkay** [comment]
I left a brief note in 68021ff848b747af0c525b11bcb27ed84343ba93

Thanks again for your help.

**Pull request merged**
